services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: goody
      POSTGRES_PASSWORD: goody123
      POSTGRES_DB: sales_db
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goody -d sales_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redis_data:
